apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: metallb-system
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 9876
      targetPort: 9876
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.168.31.140
